name: Release CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    name: Build and deploy release assets
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - name: Installing core packages
        run: |
          sudo dnf -y install git-core
      - name: Fetching sources from repository
        uses: actions/checkout@v4
      - name: Installing build dependencies
        run: |
          sudo dnf -y install \
            dejavu-sans-fonts \
            dejavu-sans-mono-fonts \
            dejavu-serif-fonts \
            latexmk \
            make \
            python3-sphinx \
            texlive-babel-russian \
            texlive-capt-of \
            texlive-cmap \
            texlive-cmcyr \
            texlive-collection-fontsrecommended \
            texlive-collection-langcyrillic \
            texlive-cyrillic-bin \
            texlive-cyrillic-bin-bin \
            texlive-fancyhdr \
            texlive-fncychap \
            texlive-framed \
            texlive-hyphen-russian \
            texlive-metafont-bin \
            texlive-needspace \
            texlive-parskip \
            texlive-polyglossia \
            texlive-tabulary \
            texlive-titlesec \
            texlive-titling \
            texlive-upquote \
            texlive-wrapfig \
            texlive-xetex \
            texlive-xindy
      - name: Building PDF using Sphinx-Doc
        run: |
          make latexpdf
      - name: Uploading built PDF artifact to releases
        uses: softprops/action-gh-release@v1
        with:
          files: build/latex/fedora-faq-ru.pdf
